/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DataBase.AdminDirectory;
import DataBase.DoctorDirectory;
import DataBase.HospitalDirectory;
import DataBase.LoginDirectory;
import DataBase.PatientDirectory;

/**
 *
 * @author Zaniar
 */
public class AView extends javax.swing.JPanel {

    /**
     * Creates new form AView
     */
    String userp;
    AdminDirectory admindirectory;
    HospitalDirectory hospitaldirectory;
    PatientDirectory patientdirectory;
    DoctorDirectory doctordirectory;
    LoginDirectory obj;
    public AView(String user,HospitalDirectory hospital,AdminDirectory admin,DoctorDirectory doctor,PatientDirectory patient,LoginDirectory obj) {
        initComponents();
        userp = user;
        this.admindirectory = admin;
        this.hospitaldirectory = hospital;
        this.patientdirectory = patient;
        this.doctordirectory = doctor;
        this.obj = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JSplitPane();
        ButtonPanel = new javax.swing.JPanel();
        AdminButton = new javax.swing.JButton();
        PatientButton = new javax.swing.JButton();
        HospitalButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        createUser = new javax.swing.JButton();
        CrudPanel = new javax.swing.JPanel();

        AdminButton.setText("Admins");
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        PatientButton.setText("Patients");
        PatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientButtonActionPerformed(evt);
            }
        });

        HospitalButton.setText("Hospitals");
        HospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Doctors");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        createUser.setText("Create");
        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HospitalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AdminButton)
                .addGap(45, 45, 45)
                .addComponent(PatientButton)
                .addGap(57, 57, 57)
                .addComponent(HospitalButton)
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(createUser)
                .addGap(198, 198, 198))
        );

        topPanel.setLeftComponent(ButtonPanel);

        javax.swing.GroupLayout CrudPanelLayout = new javax.swing.GroupLayout(CrudPanel);
        CrudPanel.setLayout(CrudPanelLayout);
        CrudPanelLayout.setHorizontalGroup(
            CrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        CrudPanelLayout.setVerticalGroup(
            CrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        topPanel.setRightComponent(CrudPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 212, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(topPanel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        // TODO add your handling code here:
        AdminCrud crudpanel = new AdminCrud(admindirectory);
        topPanel.setRightComponent(crudpanel);

    }//GEN-LAST:event_AdminButtonActionPerformed

    private void PatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientButtonActionPerformed
        // TODO add your handling code here:
        PatientCrud crudpanel = new PatientCrud(patientdirectory);
        topPanel.setRightComponent(crudpanel);
    }//GEN-LAST:event_PatientButtonActionPerformed

    private void HospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalButtonActionPerformed
        // TODO add your handling code here:
        HospitalCrud crudpanel = new HospitalCrud(hospitaldirectory);
        topPanel.setRightComponent(crudpanel);
    }//GEN-LAST:event_HospitalButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DoctorCrud crudpanel = new DoctorCrud(doctordirectory);
        topPanel.setRightComponent(crudpanel);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed
        // TODO add your handling code here:
        CreateUser create = new CreateUser(admindirectory, doctordirectory, patientdirectory,obj);
        topPanel.setRightComponent(create);
    }//GEN-LAST:event_createUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel CrudPanel;
    private javax.swing.JButton HospitalButton;
    private javax.swing.JButton PatientButton;
    private javax.swing.JButton createUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane topPanel;
    // End of variables declaration//GEN-END:variables
}
