/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DataBase.AdminDirectory;
import DataBase.DoctorDirectory;
import DataBase.LoginDirectory;
import DataBase.PatientDirectory;
import System.Admin;
import System.Doctor;
import System.Patient;
import javax.swing.JOptionPane;


/**
 *
 * @author Zaniar
 */
public class CreateUser extends javax.swing.JPanel {

    /**
     * Creates new form CreateUser
     */
    
    AdminDirectory ausers;
    DoctorDirectory dusers;
    PatientDirectory pusers;
    LoginDirectory obj;
    
    public CreateUser(AdminDirectory admin,DoctorDirectory doctor,PatientDirectory patient,LoginDirectory obj) {
        initComponents();
        this.ausers = admin;
        this.dusers = doctor;
        this.pusers = patient;
        this.obj = obj;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saveButtton = new javax.swing.JButton();
        userField = new javax.swing.JTextField();
        rollField = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();

        jLabel1.setText("Username :");

        saveButtton.setText("Save");
        saveButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButttonActionPerformed(evt);
            }
        });

        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });

        rollField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Doctor", "Admin" }));
        rollField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Password :");

        jLabel3.setText("Role :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButtton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rollField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passField)
                        .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rollField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(saveButtton)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void rollFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollFieldActionPerformed

    private void saveButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButttonActionPerformed
        // TODO add your handling code here:
        if (userField == null && passField == null){
            JOptionPane.showMessageDialog(this, "The Fields Must Be Filled");
        }else{
            String pick = rollField.getSelectedItem().toString();
            
            if("Admin".equals(pick)){
                    Admin auser = new Admin();
                    auser.setUser(userField.getText());
                    auser.setPass(passField.getText());
                    auser.setRole("Admin");
                    ausers.addUser(auser);
                    obj.getDirectoryData();
                    JOptionPane.showMessageDialog(this, "Saved Successfully");
            }else if("Patient".equals(pick)){
                    Patient puser = new Patient();
                    puser.setUser(userField.getText());
                    puser.setPass(passField.getText());
                    puser.setRole("Patient");
                    pusers.addUser(puser);
                    obj.getDirectoryData();
                    JOptionPane.showMessageDialog(this, "Saved Successfully");
            }else if(pick.equals("Doctor")){
                    Doctor duser = new Doctor();
                    duser.setUser(userField.getText());
                    duser.setPass(passField.getText());
                    duser.setRole("Doctor");
                    dusers.addUser(duser);
                    obj.getDirectoryData();
                    JOptionPane.showMessageDialog(this, "Saved Successfully");
                    
            }
        
        userField.setText("");
        passField.setText("");
       
    }//GEN-LAST:event_saveButttonActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField passField;
    private javax.swing.JComboBox<String> rollField;
    private javax.swing.JButton saveButtton;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
